services:
 zergex_postgres:
  image: postgres:13
  environment:
   - POSTGRES_DB=${PG_DATABASE}
   - POSTGRES_USER=${PG_USER}
   - POSTGRES_PASSWORD=${PG_PASSWORD}
  ports:
   - ${PG_PORT}:5432
  volumes:
   - ./postgres_data:/var/lib/postgresql/data

 zergex_pgadmin:
  image: dpage/pgadmin4
  environment:
   - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
   - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
  ports:
   - ${PGADMIN_PORT}:80
